import "./App.css";

export default function App({ notes }) {
  return (
    <div className="App">
      <h1>Notes</h1>
      <ul>
        {/* <li>{notes[0].content}</li> // This method isn't practical and your code will become bloated over time. A better an easier way to generate the list is by using map.
        <li>{notes[1].content}</li>
        <li>{notes[2].content}</li> */}

        {notes.map((note) => (
          <li key={note.id}>{note.content}</li> // React uses the key attributes of objects in an array to determine how to update the view generated by a component when the component is re-rendered. 
        ))}
      </ul>
    </div>
  );
}
